baseURL = "https://ice-cocoa.net/"
languageCode = "zh-cn"
title = "IceCocoa's blog"
theme = "github-style"
#è°·æ­Œçš„ç»Ÿè®¡å·¥å…·ï¼Œæš‚æ—¶æœªå¯ç”¨ 
#googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "ice-cocoa"
  description = "ä»Šæ—¥ã‚‚ä¸€æ—¥ãŒã‚“ã°ã‚‹ãã„ï¼"
  github = "ice-cocoa"
  #facebook = "ice-cocoa"
  #twitter = "ice-cocoa"
  #linkedin = "ice-cocoa"
  #instagram = "ice-cocoa"
  #tumblr = "ice-cocoa"
  email = "wangbonsgo@gmail.com"
  url = "https://ice-cocoa.net"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/avatar.png"
  location = "China"
  userStatusEmoji = "ğŸ¦”"
  # æš‚ä¸å¯ç”¨gittalk
  enableGitalk = false

  #æœªå¯ç”¨  
  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "ventusoon" # æ‚¨çš„GitHub ID
    admin = "ventusoon" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  #[[params.links]]
  #  title = "Link"
  #  href = "https://ice-cocoa.net"
  [[params.links]]
    title = "Link2"
    href = "https://ice-cocoa.net"
    icon = "/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
